apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: front-end
  name: front-end
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      run: front-end
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: front-end
    spec:
      containers:
      - image: REPLACE-IMAGE-NAME
        name: front-end
        ports:
        - containerPort: 80
        resources: {}
        imagePullPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: front-end
  name: front-end
  namespace: REPLACE_NAMESPACE
spec:
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 80
    name: grp3
  selector:
    run: front-end
  type: LoadBalancer
  loadBalancerIP: 10.254.36.51
status:
  loadBalancer: {}
