
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: staging
type: Opaque
data:
  database-user: YWRtaW4=
  database-password: MWYyZDFlMmU2N2Rm
---
apiVersion: v1
kind: Secret
metadata:
  name: private-registry-creds
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4yNC4yNTUuMTM1Ijp7IlVzZXJuYW1lIjoiZ2tlIiwiUGFzc3dvcmQiOiJwYXNzd29yZCIsIkVtYWlsIjoiZXhhbXBsZUBleGFtcGxlLmNvbSIsIkF1dGgiOiJaMnRsT25CaGMzTjNiM0prIn19fQ==
type: kubernetes.io/dockerconfigjson
